### ISSUE TITLE
[Bug] Singleton applications won't force relaunch

### ISSUE THREAD

**Issue by aherreraGH** [os-js/osjs-client#7]
maybe it's just for autostart. But, the application does not reload when the user clicks on "reload" in the menu option. 

Also, when npm run build:dist is completed, the apps that are set to autostart, disappear and fail to reload. Likely similar issue.

**Comment by andersevenrud** [comment]
> But, the application does not reload when the user clicks on "reload" in the menu option.

https://github.com/os-js/osjs-client/blob/master/src/application.js#L178

As you can see here, this is because it tries to launch before the original application is destroyed. I'll fix this.

> Also, when npm run build:dist is completed, the apps that are set to autostart, disappear and fail to reload. Likely similar issue.

Not sure I understand this. If you have compilation errors, then they *will* fail, otherwise there should be no issue. Do you mean the hot-reloading or when you refresh the browser ?

**Comment by aherreraGH** [comment]
No compile errors.  Yes, hot-reloading.

**Comment by andersevenrud** [comment]
Ah, yes. The hot-reload uses the reload function, so this is a related issue :)

**Comment by andersevenrud** [comment]
I've commited a fix for this and should be published now.
